version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pricing-backend
    ports:
      - "5002:5002"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - pricing-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: pricing-frontend
    ports:
      - "8501:8501"
    environment:
      - ML_API_URL=http://backend:5002
      - PYTHONUNBUFFERED=1
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    networks:
      - pricing-network

networks:
  pricing-network:
    driver: bridge

volumes:
  pricing-data:
    driver: local
